import { Deal } from '@/lib/types/deal';

export interface DealTemplate {
  id: string;
  name: string;
  emoji: string;
  description: string;
  tags: string[];
  typical: string; // e.g. "Yield 6–10% · Cash purchase"
  overrides: Partial<Omit<Deal, 'id' | 'createdAt' | 'updatedAt' | 'analysis' | 'buyerProfile'>>;
}

export const DEAL_TEMPLATES: DealTemplate[] = [
  {
    id: 'leilao',
    name: 'Leilão Judicial',
    emoji: '⚖️',
    description: 'Judicial or extrajudicial auction property. Usually 30–50% below market, but requires cash and carries regularisation risk.',
    tags: ['Cash only', 'High discount', 'Renovation needed'],
    typical: 'Discount 30–50% · Cash · Renovation required',
    overrides: {
      name: 'Leilão — untitled',
      status: 'draft',
      property: {
        address: '',
        city: '',
        neighborhood: '',
        state: 'SP',
        country: 'BR',
        propertyType: 'apartment',
        purchaseStrategy: 'buy-to-sell',
        askingPrice: 0,
        currency: 'BRL',
        sizeSqm: 0,
        rooms: 2,
        bathrooms: 1,
        parkingSpaces: 1,
        condition: 'renovation',
        isNewDevelopment: false,
        hasHabitese: false, // may lack habite-se
      },
      financing: {
        financingType: 'cash',
        downPaymentPercent: 100,
        downPaymentAmount: 0,
        loanAmount: 0,
        interestRate: 0,
        loanTermYears: 20,
        loanType: 'SAC',
        usesFGTS: false,
        financedByMCMV: false,
      },
      rentalAssumptions: {
        strategy: 'long-term',
        ltr: {
          monthlyRent: 0,
          annualRentGrowthPercent: 5,
          vacancyRatePercent: 8,
          managementFeePercent: 8,
          maintenancePercent: 0.5,
          insurance: 0,
        },
        str: {
          avgNightlyRate: 0,
          occupancyRatePercent: 60,
          cleaningFeePerStay: 80,
          platformCommissionPercent: 15,
          managementFeePercent: 20,
          maintenancePercent: 0.8,
          insurance: 0,
          utilitiesMontly: 400,
          monthlyMultipliers: [],
        },
      },
      userOverrides: {
        notes: `LEILÃO CHECKLIST:\n☐ Verify arrematação minimum value (50% or 30% of avaliação)\n☐ Check for outstanding IPTU/condomínio debts (buyer's responsibility)\n☐ Confirm habite-se status — may need regularização\n☐ Check for tenants / occupants (desocupação can take months)\n☐ Research property for any liens beyond the auctioned debt\n☐ Confirm if bank financing is possible for this auction type\n☐ Budget for renovation + regularisation costs`,
      },
    },
  },
  {
    id: 'planta',
    name: 'Imóvel na Planta',
    emoji: '🏗️',
    description: 'Off-plan / pre-launch purchase. Typically 20–30% cheaper than ready units, with staged payments during construction (2–4 years).',
    tags: ['Off-plan', 'Lower entry', 'Long horizon'],
    typical: 'Appreciation play · Staged payments · 2–4yr delivery',
    overrides: {
      name: 'Planta — untitled',
      status: 'draft',
      property: {
        address: '',
        city: '',
        neighborhood: '',
        state: 'SP',
        country: 'BR',
        propertyType: 'apartment',
        purchaseStrategy: 'buy-to-let',
        askingPrice: 0,
        currency: 'BRL',
        sizeSqm: 0,
        rooms: 2,
        bathrooms: 2,
        parkingSpaces: 1,
        condition: 'new',
        isNewDevelopment: true,
        hasHabitese: false,
      },
      financing: {
        financingType: 'caixa',
        downPaymentPercent: 30,
        downPaymentAmount: 0,
        loanAmount: 0,
        interestRate: 10.99,
        loanTermYears: 25,
        loanType: 'SAC',
        usesFGTS: false,
        financedByMCMV: false,
      },
      rentalAssumptions: {
        strategy: 'long-term',
        ltr: {
          monthlyRent: 0,
          annualRentGrowthPercent: 6,
          vacancyRatePercent: 5,
          managementFeePercent: 8,
          maintenancePercent: 0.3, // new unit, lower maintenance
          insurance: 0,
        },
        str: {
          avgNightlyRate: 0,
          occupancyRatePercent: 65,
          cleaningFeePerStay: 80,
          platformCommissionPercent: 15,
          managementFeePercent: 20,
          maintenancePercent: 0.5,
          insurance: 0,
          utilitiesMontly: 400,
          monthlyMultipliers: [],
        },
      },
      userOverrides: {
        notes: `PLANTA CHECKLIST:\n☐ Verify incorporadora's track record (CRECI, RGI registrations)\n☐ Check memorial descritivo (specifications) carefully\n☐ Confirm INCC correction index applies to parcelas during construction\n☐ Understand distrato rules (Lei 13.786/2018)\n☐ Verify entrega date + penalty clauses for delays\n☐ Budget for: taxa de corretagem, ITBI on delivery, condomínio setup\n☐ First rent may be 6–12 months after entrega (finishing time)`,
      },
    },
  },
  {
    id: 'kitnet',
    name: 'Kitnet / Studio',
    emoji: '🏠',
    description: 'Small rental unit optimised for yield. High demand near universities and business districts, low ticket, can work for STR.',
    tags: ['High yield', 'Low ticket', 'STR friendly'],
    typical: 'Yield 7–12% · STR or LTR · 20–40m²',
    overrides: {
      name: 'Kitnet — untitled',
      status: 'draft',
      property: {
        address: '',
        city: '',
        neighborhood: '',
        state: 'SP',
        country: 'BR',
        propertyType: 'studio',
        purchaseStrategy: 'buy-to-let',
        askingPrice: 0,
        currency: 'BRL',
        sizeSqm: 30,
        rooms: 1,
        bathrooms: 1,
        parkingSpaces: 0,
        condition: 'good',
        isNewDevelopment: false,
        hasHabitese: true,
      },
      financing: {
        financingType: 'private-bank',
        downPaymentPercent: 30,
        downPaymentAmount: 0,
        loanAmount: 0,
        interestRate: 11.49,
        loanTermYears: 20,
        loanType: 'SAC',
        usesFGTS: false,
        financedByMCMV: false,
      },
      rentalAssumptions: {
        strategy: 'short-term',
        ltr: {
          monthlyRent: 0,
          annualRentGrowthPercent: 5,
          vacancyRatePercent: 6,
          managementFeePercent: 8,
          maintenancePercent: 0.6,
          insurance: 0,
        },
        str: {
          avgNightlyRate: 0,
          occupancyRatePercent: 70,
          cleaningFeePerStay: 60,
          platformCommissionPercent: 15,
          managementFeePercent: 25,
          maintenancePercent: 1.0,
          insurance: 0,
          utilitiesMontly: 300,
          monthlyMultipliers: [],
        },
      },
      userOverrides: {},
    },
  },
  {
    id: 'casa-condominio',
    name: 'Casa em Condomínio',
    emoji: '🏡',
    description: 'House in a gated community (condomínio fechado). Lower yield but stronger appreciation, security premium, and family demand.',
    tags: ['Lower yield', 'Appreciation', 'Family demand'],
    typical: 'Yield 4–6% · Long-term hold · Gated community',
    overrides: {
      name: 'Casa em Condomínio — untitled',
      status: 'draft',
      property: {
        address: '',
        city: '',
        neighborhood: '',
        state: 'SP',
        country: 'BR',
        propertyType: 'house',
        purchaseStrategy: 'buy-to-let',
        askingPrice: 0,
        currency: 'BRL',
        sizeSqm: 200,
        rooms: 3,
        bathrooms: 3,
        parkingSpaces: 2,
        condition: 'good',
        isNewDevelopment: false,
        hasHabitese: true,
      },
      financing: {
        financingType: 'private-bank',
        downPaymentPercent: 25,
        downPaymentAmount: 0,
        loanAmount: 0,
        interestRate: 11.99,
        loanTermYears: 20,
        loanType: 'SAC',
        usesFGTS: false,
        financedByMCMV: false,
      },
      rentalAssumptions: {
        strategy: 'long-term',
        ltr: {
          monthlyRent: 0,
          annualRentGrowthPercent: 5,
          vacancyRatePercent: 6,
          managementFeePercent: 8,
          maintenancePercent: 0.7,
          insurance: 0,
        },
        str: {
          avgNightlyRate: 0,
          occupancyRatePercent: 55,
          cleaningFeePerStay: 150,
          platformCommissionPercent: 15,
          managementFeePercent: 20,
          maintenancePercent: 0.9,
          insurance: 0,
          utilitiesMontly: 600,
          monthlyMultipliers: [],
        },
      },
      userOverrides: {
        notes: `CONDOMÍNIO NOTES:\n☐ Confirm monthly taxa de condomínio (often R$800–2,500)\n☐ Check fundo de reserva and any pending assessments\n☐ Review condomínio regulations for rental/STR rules\n☐ Confirm IPTU — houses typically higher than apartments`,
      },
    },
  },
  {
    id: 'comercial',
    name: 'Imóvel Comercial',
    emoji: '🏢',
    description: 'Commercial property (sala, loja, escritório). Higher cap rates, longer leases, but different tax treatment and vacancy risk.',
    tags: ['Higher cap rate', 'Commercial lease', 'PJ buyer'],
    typical: 'Cap rate 6–10% · Longer leases · CNPJ recommended',
    overrides: {
      name: 'Comercial — untitled',
      status: 'draft',
      property: {
        address: '',
        city: '',
        neighborhood: '',
        state: 'SP',
        country: 'BR',
        propertyType: 'commercial',
        purchaseStrategy: 'buy-to-let',
        askingPrice: 0,
        currency: 'BRL',
        sizeSqm: 60,
        rooms: 1,
        bathrooms: 1,
        parkingSpaces: 1,
        condition: 'good',
        isNewDevelopment: false,
        hasHabitese: true,
      },
      financing: {
        financingType: 'private-bank',
        downPaymentPercent: 35,
        downPaymentAmount: 0,
        loanAmount: 0,
        interestRate: 12.49,
        loanTermYears: 15,
        loanType: 'SAC',
        usesFGTS: false,
        financedByMCMV: false,
      },
      rentalAssumptions: {
        strategy: 'long-term',
        ltr: {
          monthlyRent: 0,
          annualRentGrowthPercent: 4,
          vacancyRatePercent: 10, // higher commercial vacancy
          managementFeePercent: 8,
          maintenancePercent: 0.5,
          insurance: 0,
        },
        str: {
          avgNightlyRate: 0,
          occupancyRatePercent: 50,
          cleaningFeePerStay: 100,
          platformCommissionPercent: 15,
          managementFeePercent: 20,
          maintenancePercent: 0.8,
          insurance: 0,
          utilitiesMontly: 500,
          monthlyMultipliers: [],
        },
      },
      userOverrides: {
        notes: `COMERCIAL NOTES:\n☐ Commercial leases (Lei 8.245/91) have different rules than residential\n☐ Tenant often pays IPTU and condomínio (verify in lease)\n☐ Consider PJ (LTDA) purchase for tax efficiency on rental income\n☐ Vacancy risk higher than residential — budget 10–15%\n☐ Confirm zoning (uso do solo) allows your intended use`,
      },
    },
  },
];
