import { Deal } from '@/lib/types/deal';

export function buildSampleDeal(): Omit<Deal, 'id' | 'createdAt' | 'updatedAt' | 'analysis'> {
  return {
    name: 'Pinheiros 2BR — Sample Deal',
    status: 'draft',
    pipelineStatus: 'exploring',
    buyerProfile: {
      citizenshipStatus: 'foreigner',
      nationalities: ['IL'],
      taxResidency: 'OTHER',
      isRomanianPassportHolder: false,
      isEUCitizen: false,
      brazilianCPF: false,
      isCompanyPurchase: false,
      existingPropertiesInBrazil: 0,
      existingPropertiesAbroad: 1,
      isFirstHomeBuyer: false,
    },
    property: {
      address: 'Rua dos Pinheiros, 500',
      city: 'São Paulo',
      neighborhood: 'Pinheiros',
      state: 'SP',
      country: 'BR',
      propertyType: 'apartment',
      purchaseStrategy: 'buy-to-let',
      askingPrice: 870000,
      agreedPrice: 840000,
      currency: 'BRL',
      sizeSqm: 78,
      rooms: 2,
      bathrooms: 2,
      parkingSpaces: 1,
      condition: 'good',
      yearBuilt: 2015,
      isNewDevelopment: false,
      hasHabitese: true,
      iptuAnnual: 3200,
      condominiumMonthly: 850,
    },
    financing: {
      financingType: 'caixa',
      downPaymentPercent: 20,
      downPaymentAmount: 168000,
      loanAmount: 672000,
      interestRate: 10.99,
      loanTermYears: 20,
      loanType: 'SAC',
      usesFGTS: false,
      financedByMCMV: false,
    },
    rentalAssumptions: {
      strategy: 'long-term',
      ltr: {
        monthlyRent: 4500,
        annualRentGrowthPercent: 5,
        vacancyRatePercent: 5,
        managementFeePercent: 8,
        maintenancePercent: 0.5,
        insurance: 0,
      },
      str: {
        avgNightlyRate: 320,
        occupancyRatePercent: 62,
        cleaningFeePerStay: 90,
        platformCommissionPercent: 15,
        managementFeePercent: 20,
        maintenancePercent: 0.8,
        insurance: 0,
        utilitiesMontly: 400,
        monthlyMultipliers: [],
      },
    },
    userOverrides: {},
  };
}
